### PR TITLE
New amazing feature

### PR DESCRIPTION
**Pull request by PhilippHoellmer**
I implemented an amazing feature you should definitely pull!

### CODE REVIEW

**Comment by WernerKrauth** [comment]
Dear Philipp, nice to meet you, and many thanks for your contribution, which was just reviewed by the JeLLyFysh team.
You understand that statements of "I", "You", etc are not easily tracked to the individual who proposed the change. We also prefer to refrain from outright boasting. 
Therefore, please change line 2 into "But PhilippHoellmer's idea appears promising"

**Comment by PhilippHoellmer** [comment]
Dear Werner, thanks for the fast reply and review! I agree with the changes and just pushed it.

**Comment by WernerKrauth** [comment]
Dear Philipp. 
Beautiful work. Very elegant. Please add your name to CONTRIBUTING.md. please use the same format as all the others.

**Comment by PhilippHoellmer** [comment]
Dear Werner,
done and pushed. Thanks again for the review!

**Comment by WernerKrauth** [comment]
Dear Philipp, this looks good to me. However, you will understand that YeLLyFysh integration rules require us to run the entire suite of Unit Tests on ANY pull request. You'll hear from us shortly. With

**Comment by PhilippHoellmer** [comment]
Dear Werner, sure! Although I already ran the test suite, so there shouldn't be any problems.

**Comment by WernerKrauth** [comment]
Dear Philipp, Thanks again for your contribution. The JeLLyFysh team just reported an unbelievable 37% score on what you did. So, although we'll have to train you, so that you understand unit tests, we'd be happy to hear from you again. In the meantime, let me merge your request. Your contribution will be useful to many people.

**Pull request merged**
