### PR TITLE
added maggs

### PR DESCRIPTION
**Pull request by acmaggs**
here I am again, tony

### CODE REVIEW

**Comment by acmaggs** [comment]
this is comment

**Comment by WernerKrauth** [comment]
Thanks Tony, happy to meet you, and thanks for your contribution. The JellyFysh team will take a look and get back to you.

**Comment by WernerKrauth** [comment]
Dear Tony,  thanks for your contribution, You'll understand that we're not quite ready to add you to the contributors.

**Comment by WernerKrauth** [comment]
Thanks, this is a major contribution. Thanks so much. I have to consult with the team, though.

**Comment by WernerKrauth** [comment]
Thanks Tony, the team said that your insight is absolutely mindblowing. Thanks. I'll now merge. Werner

**Pull request merged**
