### PR TITLE
i solved a+b problem

### PR DESCRIPTION
**Pull request by LiangQinatFr**
much much faster!

### CODE REVIEW

**Comment by LiangQinatFr** [comment]
I can still comment!

**Comment by WernerKrauth** [comment]
Thanks LiangQin. Very happy to see that you are interested in our Project. It so happens that one member of the JeLLyFysh project has the same name as you. What a coincidence!
Our team will now review your request. BTW: Did you run unit tests?
Thanks again, Werner

**Comment by WernerKrauth** [comment]
Dear LiangQin,
It was suggested that you output 'a + b = ' 30, rather than just the number 30. Please also output the input. 
Thanks, Werner (for the JeLLyFysh team)

**Comment by WernerKrauth** [comment]
Thanks LiangQin. The JeLLyFysh team judges your contribution as wonderful. Thanks a lot, 

Werner

**Pull request merged**
